#!/usr/bin/env bash
# build-with-plugins.sh — generate plugin_imports.go from a list of module paths.
#
# Usage: scripts/build-with-plugins.sh <module[@version]> [...]
# Example: scripts/build-with-plugins.sh \
#            github.com/benwiebe/udb-plugin-nhl@v1.2.0 \
#            github.com/benwiebe/udb-plugin-samples
#
# Invoked automatically by: make build PLUGINS="<module> [<module> ...]"
#
# This script:
#   1. Fetches each module that is not already provided by the workspace
#   2. Overwrites plugin_imports.go with the appropriate blank imports
#
# The resulting plugin_imports.go should be committed if this is an intentional
# custom build, or left uncommitted for one-off builds.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
IMPORTS_FILE="$REPO_ROOT/plugin_imports.go"

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 <module[@version]> [...]" >&2
    exit 1
fi

echo "Fetching plugin modules..."
for module in "$@"; do
    go get "$module"
done

echo "Generating $IMPORTS_FILE..."
{
    printf 'package main\n'
    printf '\n'
    printf '// Code generated by scripts/build-with-plugins.sh — do not edit manually.\n'
    printf '// Regenerate with: make build PLUGINS="<module> [<module> ...]"\n'
    printf '\n'
    printf 'import (\n'
    for module in "$@"; do
        # Strip version suffix (e.g. @v1.2.0) to get the import path
        import_path="${module%@*}"
        printf '\t_ "%s"\n' "$import_path"
    done
    printf ')\n'
} > "$IMPORTS_FILE"

echo "Done. $# plugin(s) configured:"
for module in "$@"; do
    echo "  ${module%@*}"
done
